const obj = {
  message: "sukses mendapatkan agent",
  code: 200,
  success: true,
  data: {
    id: 2,
    username: "peoplebcc",
    email: "siapa@gmail.com",
    password: "$2a$10$hjdi1S7M7zF3qhHskzoKHulBrrOs.qEgCXpM9.aKyCG1ZUcq1j/c6",
    namaBadanUsaha: "Power Rangers",
    namaPIC: null,
    kontakPIC: null,
    alamatKantor: null,
    kontakAdminKantor: null,
    whatsappKantor: null,
    linkAkunInstagram: null,
    suratIzinUsaha: null,
    fotoProfil: null,
    linkGmaps: null,
    linkAkunTelegram: null,
    linkAkunFacebook: null,
    linkAkunLine: null,
    linkAkunTwitter: null,
    bio: null,
    statusVerified: "BELUM_TERVERIFIKASI",
    aboutMe: null,
    premiumDate: null,
    portofolio: [],
    createdAt: "2023-01-08",
    updatedAt: "2023-01-08",
    deletedAt: null,
    trip: [],
    role: "AGENT",
    paymentExpired: false,
  },
};
